# Generated by Django 4.0.1 on 2022-03-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beautyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('photo_id', models.IntegerField()),
                ('photo_edited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='bokehReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('photo_id', models.IntegerField()),
                ('photo_edited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='editReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('photo_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('rate', models.IntegerField(default=1)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FileEditable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('uploaded_date', models.DateField()),
                ('review', models.TextField(blank=True)),
                ('photo_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='hdrReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('photo_id', models.IntegerField()),
                ('photo_edited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='lightReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('photo_id', models.IntegerField()),
                ('photo_edited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('email', models.CharField(max_length=60)),
                ('uploaded_date', models.DateField()),
                ('uploaded_time', models.TimeField()),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
    ]
